### ISSUE TITLE
Symfony ~2.6 Support

### ISSUE THREAD

**Issue by adamgoose** [mcrumm/phlack#12]
When using Symfony 2.7 (with Laravel 5.0), I get the following exception.

```
[2015-06-04 22:25:58] local.ERROR: exception 'ErrorException' with message 'The Symfony\Component\OptionsResolver\OptionsResolver::setOptional method is deprecated since version 2.6 and will be removed in 3.0. Use the setDefined() method instead.' in /home/vagrant/Sites/bugsnag-server/vendor/symfony/options-resolver/OptionsResolver.php:1111
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(16384, 'The Symfony\\Com...', '/home/vagrant/S...', 1111, Array)
#1 /home/vagrant/Sites/bugsnag-server/vendor/symfony/options-resolver/OptionsResolver.php(1111): trigger_error('The Symfony\\Com...', 16384)
#2 /home/vagrant/Sites/bugsnag-server/vendor/mcrumm/phlack/src/Crummy/Phlack/Common/Hash.php(90): Symfony\Component\OptionsResolver\OptionsResolver->setOptional(Array)
#3 /home/vagrant/Sites/bugsnag-server/vendor/mcrumm/phlack/src/Crummy/Phlack/Message/Message.php(36): Crummy\Phlack\Common\Hash->setDefaultOptions(Object(Symfony\Component\OptionsResolver\OptionsResolver))
#4 /home/vagrant/Sites/bugsnag-server/vendor/mcrumm/phlack/src/Crummy/Phlack/Common/Hash.php(22): Crummy\Phlack\Message\Message->setDefaultOptions(Object(Symfony\Component\OptionsResolver\OptionsResolver))
#5 /home/vagrant/Sites/bugsnag-server/vendor/mcrumm/phlack/src/Crummy/Phlack/Message/Message.php(28): Crummy\Phlack\Common\Hash->__construct(Array)
#6 /home/vagrant/Sites/bugsnag-server/vendor/mcrumm/phlack/src/Crummy/Phlack/Builder/MessageBuilder.php(38): Crummy\Phlack\Message\Message->__construct('Uncaught Except...', 'notifications', 'BridgeConX BugS...', 'dizzy_face')
#7 /home/vagrant/Sites/bugsnag-server/app/Commands/NotifySlackOfIncomingNotificationCommand.php(37): Crummy\Phlack\Builder\MessageBuilder->create()
#8 [internal function]: BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand->handle(Object(Crummy\Phlack\Phlack), Object(Illuminate\Config\Repository))
#9 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#10 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(202): Illuminate\Container\Container->call(Array)
#11 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#12 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#14 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#15 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(215): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(185): Illuminate\Bus\Dispatcher->dispatchNow(Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand), NULL)
#17 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesCommands.php(15): Illuminate\Bus\Dispatcher->dispatch(Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#18 /home/vagrant/Sites/bugsnag-server/app/Commands/StoreNewNotificationCommand.php(50): BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand->dispatch(Object(BridgeConX\BugsnagServer\Commands\NotifySlackOfIncomingNotificationCommand))
#19 [internal function]: BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand->handle(Object(Illuminate\Config\Repository))
#20 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#21 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(202): Illuminate\Container\Container->call(Array)
#22 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#23 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#25 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#26 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(215): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(185): Illuminate\Bus\Dispatcher->dispatchNow(Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand), NULL)
#28 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesCommands.php(15): Illuminate\Bus\Dispatcher->dispatch(Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#29 /home/vagrant/Sites/bugsnag-server/app/Http/Controllers/NotificationController.php(15): BridgeConX\BugsnagServer\Http\Controllers\Controller->dispatch(Object(BridgeConX\BugsnagServer\Commands\StoreNewNotificationCommand))
#30 [internal function]: BridgeConX\BugsnagServer\Http\Controllers\NotificationController->notify(Object(BridgeConX\BugsnagServer\Http\Requests\NotificationRequest))
#31 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#32 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('notify', Array)
#33 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(BridgeConX\BugsnagServer\Http\Controllers\NotificationController), Object(Illuminate\Routing\Route), 'notify')
#34 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(BridgeConX\BugsnagServer\Http\Controllers\NotificationController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'notify')
#40 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'BridgeConX\\Bugs...', 'notify')
#41 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#42 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#49 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#50 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(214): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#52 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /home/vagrant/Sites/bugsnag-server/app/Http/Middleware/VerifyCsrfToken.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): BridgeConX\BugsnagServer\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/vagrant/Sites/bugsnag-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#69 /home/vagrant/Sites/bugsnag-server/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#70 {main}  
```

**Comment by mcrumm** [comment]
Well, that's problematic...

I likely won't get around to actually _fixing_ this error, since I'll be deprecating this library in the very near future, due to lack of time to keep it updated, but I will certainly update composer to reflect the supported versions of Symfony's OptionsResolver.

Given that you're using Laravel, may I suggest [maknz/slack](https://github.com/maknz/slack)? Laravel support included out-of-the-box, very similar implementation, and much more frequent updates.

Thanks for letting me know!

**Comment by adamgoose** [comment]
Thanks. That's what I ended up doing. :P I typically like to write my own Service Providers so I can configure it how I want anyway. So Laravel out-of-the-box capabilities is not something I look for in a package.

**Comment by mcrumm** [comment]
Fair enough.  I'm glad to hear you were able to get something working.  I'm going to leave this issue open to remind myself to fix the composer dependencies.  Thanks, again!

**Comment by mcrumm** [comment]
It took a little bit of doing, but I was able to update to allow for newer versions of [symfony/options-resolver](https://packagist.org/packages/symfony/options-resolver) without breaking compatibility with v2.4.  Looks like the Symfony devs are going back and forth about how to handle deprecated methods, too, because v2.7.0+ call `trigger_error`, but v2.7.1+ suppress the triggered error.

Either way, Phlack is now compatible with `symfony/options-resolver >= 2.4.0`.  Thanks, again, for the bug report!
